# Generated by Django 4.0.6 on 2022-10-15 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Devlog(0.0.0) The Title Here', max_length=200)),
                ('bg_image', models.ImageField(upload_to='images/devlogs/')),
                ('short_description', models.CharField(default='Placeholder Short Description', max_length=400)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Development and Production', (('BUGS', 'Bug Fixing'), ('DEV', 'Development'), ('ANNO', 'Announcement'))), ('Games', [('DND5E', 'Dungeons and Dragons 5e'), ('TOR20', 'Tormenta20'), ('PAF1e', 'Pathfinder 1e')])], max_length=32)),
                ('devlog_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentications.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DevLogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.profile')),
                ('devlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devlogs.devlog')),
            ],
        ),
    ]
