# Generated by Django 4.0.6 on 2022-11-20 19:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devlog',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Development and Production', (('BUGS', 'Bug Fixing'), ('DEV', 'Development'), ('ANNO', 'Announcement'))), ('Games', [('DND5E', 'Dungeons and Dragons 5e'), ('TOR20', 'Tormenta20'), ('PAF1e', 'Pathfinder 1e'), ('CoC7e', 'Call of Cthulhu 7e')])], max_length=32),
        ),
    ]
