# Generated by Django 4.0.6 on 2022-08-16 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('O', 'Other Issues'), ('M', 'Monsters'), ('F', 'Found a Bug'), ('A', 'Add a Game'), ('T', 'Add a Translation')], default='O', max_length=1)),
                ('request_title', models.CharField(max_length=50)),
                ('request_text', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
