# Generated by Django 4.0.6 on 2022-10-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('O', 'Other'), ('M', 'Monsters'), ('A', 'Add new Game'), ('T', 'Add new Translation'), ('B', 'Found a Bug')], default='', max_length=1)),
                ('request_title', models.CharField(max_length=50)),
                ('request_text', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.profile')),
            ],
        ),
    ]
