# Generated by Django 4.0.6 on 2022-11-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspells',
            name='casting_time',
            field=models.CharField(max_length=255),
        ),
    ]
