# Generated by Django 4.0.6 on 2022-11-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_alter_dndspells_casting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspells',
            name='materials_needed',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
