# Generated by Django 4.0.6 on 2022-11-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_alter_dndspells_materials_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspells',
            name='materials_needed',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
