# Generated by Django 4.0.6 on 2022-08-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('is_attack', models.BooleanField(default=False)),
                ('weapon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('reach', models.CharField(blank=True, max_length=50, null=True)),
                ('hit', models.IntegerField(blank=True, null=True)),
                ('hit_dice', models.CharField(blank=True, max_length=10, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
