# Generated by Django 4.0.6 on 2022-08-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='documents/manuals/<django.db.models.fields.CharField>')),
                ('language', models.CharField(choices=[('PT', 'Portugues'), ('EN', 'English')], max_length=2)),
            ],
        ),
    ]
