# Generated by Django 4.0.6 on 2022-08-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='category',
            field=models.CharField(choices=[('MON', 'Monsters'), ('PLA', 'PlayerBooks'), ('GMS', 'Game Masters Guides')], default='MON', max_length=3),
        ),
        migrations.AlterField(
            model_name='manual',
            name='language',
            field=models.CharField(choices=[('PT', 'Portuguese'), ('EN', 'English')], max_length=2),
        ),
    ]
