# Generated by Django 4.0.6 on 2022-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_manual_category_alter_manual_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='image',
            field=models.ImageField(default='', upload_to='documents/manuals/imgs/<django.db.models.fields.CharField>'),
        ),
    ]
