# Generated by Django 4.0.6 on 2022-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_manual_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='image',
            field=models.ImageField(default=None, upload_to='documents/manuals/imgs/<django.db.models.fields.CharField>'),
        ),
    ]
