# Generated by Django 4.0.6 on 2022-08-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0005_remove_manual_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='image',
            field=models.ImageField(default='', upload_to='documents/manuals/thumbs/'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='file_path',
            field=models.FileField(upload_to='documents/manuals/'),
        ),
    ]
