# Generated by Django 4.0.6 on 2022-08-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0007_alter_manual_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
