# Generated by Django 4.0.6 on 2022-08-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('ac', models.IntegerField()),
                ('ac_type', models.CharField(max_length=20)),
                ('hp', models.IntegerField()),
                ('hp_dices', models.CharField(max_length=10)),
                ('movement', models.CharField(max_length=30)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('languages', models.CharField(default='None', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('basesheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monsters.basesheet')),
                ('challenge', models.CharField(default='0', max_length=3)),
                ('description', models.TextField(default='')),
            ],
            bases=('monsters.basesheet',),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('is_attack', models.BooleanField(default=False)),
                ('weapon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('reach', models.CharField(blank=True, max_length=50, null=True)),
                ('hit', models.IntegerField(blank=True, null=True)),
                ('hit_dice', models.CharField(blank=True, max_length=10, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.monster')),
            ],
        ),
    ]
