# Generated by Django 4.0.6 on 2022-08-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesheet',
            name='teste',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
