# Generated by Django 4.0.6 on 2022-08-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesheet',
            name='languages',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.ManyToManyField(to='actions.action'),
        ),
    ]
