# Generated by Django 4.0.6 on 2022-10-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesheet',
            name='hp_dices',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dndmonster',
            name='condition_immunities',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dndmonster',
            name='damage_immunities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dndmonster',
            name='damage_resistances',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='immune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
