# Generated by Django 4.0.6 on 2022-11-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndaction',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
