# Generated by Django 4.0.6 on 2022-11-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesheet',
            name='hp_dices',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='movement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dndmonster',
            name='condition_immunities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dndmonster',
            name='damage_immunities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dndmonster',
            name='damage_resistances',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='ac_mod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='aura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='fortitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='hp_mod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='immune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='init',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='monster_alignment',
            field=models.CharField(choices=[('LG', 'Lawful Good'), ('LN', 'Lawful Neutral'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('CG', 'Chaotic Good'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil')], default='N', max_length=100),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='monster_class',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='reflex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='resist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='save_mods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='senses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='special_qualities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='subtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='will',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathfinderoffense',
            name='attack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfinderoffense',
            name='effect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfinderoffense',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
