# Generated by Django 4.0.6 on 2022-11-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocmonster',
            name='attacks_per_round',
        ),
    ]
