<<<<<<<< HEAD:monsters/migrations/0002_alter_dndaction_hit_dice.py
# Generated by Django 4.0.6 on 2022-11-17 22:54
========
# Generated by Django 4.0.6 on 2022-11-15 00:56
>>>>>>>> deploy:monsters/migrations/0004_alter_dndaction_hit_dice.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:monsters/migrations/0002_alter_dndaction_hit_dice.py
        ('monsters', '0001_initial'),
========
        ('monsters', '0003_alter_basesheet_charisma_and_more'),
>>>>>>>> deploy:monsters/migrations/0004_alter_dndaction_hit_dice.py
    ]

    operations = [
        migrations.AlterField(
            model_name='dndaction',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
