# Generated by Django 4.0.6 on 2022-11-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_alter_basesheet_hp_dices_alter_basesheet_movement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesheet',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
