# Generated by Django 4.0.6 on 2022-10-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_alter_basesheet_hp_dices_alter_basesheet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='immune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
