# Generated by Django 4.0.6 on 2022-08-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_basesheet_languages_monster_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesheet',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
