# Generated by Django 4.0.6 on 2022-08-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_profile_email_profile_username'),
        ('monsters', '0002_basesheet_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesheet',
            name='teste',
        ),
        migrations.AlterField(
            model_name='basesheet',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentications.profile'),
        ),
    ]
