# Generated by Django 4.0.6 on 2022-10-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_alter_pathfindermonster_immune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='aura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
