# Generated by Django 4.0.6 on 2022-11-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_alter_basesheet_charisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndaction',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
