# Generated by Django 4.0.6 on 2022-08-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('monsters', '0003_alter_basesheet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='actions',
        ),
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='actions.action'),
            preserve_default=False,
        ),
    ]
