# Generated by Django 4.0.6 on 2022-08-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_alter_monster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='alignment',
            field=models.CharField(default='Neutral', max_length=30),
        ),
        migrations.AddField(
            model_name='monster',
            name='senses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SpecialTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.monster')),
            ],
        ),
    ]
