# Generated by Django 4.0.6 on 2022-11-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name='dndaction',
            name='action_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dndaction',
            name='damage_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dndaction',
            name='weapon_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
