# Generated by Django 4.0.6 on 2022-08-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('monsters', '0004_remove_monster_actions_monster_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='actions',
        ),
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.ManyToManyField(to='actions.action'),
        ),
    ]
