# Generated by Django 4.0.6 on 2022-08-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0004_monster_alignment_monster_senses_specialtraits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.monster')),
            ],
        ),
    ]
