# Generated by Django 4.0.6 on 2022-10-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0004_alter_pathfindermonster_aura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='resist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
