# Generated by Django 4.0.6 on 2022-10-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_alter_pathfindermonster_resist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='monster_class',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
