# Generated by Django 4.0.6 on 2022-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='modifier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Athletics', 'Athletics'), ('Acrobatics', 'Acrobatics'), ('Sleight of Hand', 'Sleight of Hand'), ('Stealth', 'Stealth'), ('Arcana', 'Arcana'), ('History', 'History'), ('Investigation', 'Investigation'), ('Nature', 'Nature'), ('Religion', 'Religion'), ('Animal Handling', 'Animal Handling'), ('Insight', 'Insight'), ('Medicine', 'Medicine'), ('Perception', 'Perception'), ('Survival', 'Survival'), ('Deception', 'Deception'), ('Intimidation', 'Intimidation'), ('Performance', 'Performance'), ('Persuasion', 'Persuasion')], max_length=15),
        ),
    ]
