# Generated by Django 4.0.6 on 2022-10-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0006_alter_pathfindermonster_monster_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
