# Generated by Django 4.0.6 on 2022-08-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0006_skill_modifier_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesheet',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
