# Generated by Django 4.0.6 on 2022-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0007_alter_pathfindermonster_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='special_qualities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
