# Generated by Django 4.0.6 on 2022-08-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0008_rename_action_dndaction_rename_monster_dndmonster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnDSavingThrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=3)),
                ('bonus', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='dndmonster',
            options={'verbose_name': 'DnD Monster'},
        ),
    ]
