# Generated by Django 4.0.6 on 2022-08-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0009_dndsavingthrows_alter_dndmonster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndsavingthrows',
            name='monster',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='monsters.dndmonster'),
        ),
    ]
