# Generated by Django 4.0.6 on 2022-08-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0010_dndsavingthrows_monster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dndaction',
            options={'verbose_name': 'DnD Action'},
        ),
        migrations.AlterModelOptions(
            name='dndsavingthrows',
            options={'verbose_name': 'DnD Saving Throw'},
        ),
        migrations.AlterModelOptions(
            name='dndskill',
            options={'verbose_name': 'DnD Skill'},
        ),
        migrations.AlterModelOptions(
            name='dndspecialtraits',
            options={'verbose_name': 'DnD Special Trait'},
        ),
        migrations.AddField(
            model_name='dndmonster',
            name='condition_immunities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dndmonster',
            name='damage_immunities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dndmonster',
            name='damage_resistances',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
