# Generated by Django 4.0.6 on 2022-10-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0010_alter_pathfindermonster_senses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
