# Generated by Django 4.0.6 on 2022-08-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0011_alter_dndaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.dndmonster')),
            ],
            options={
                'verbose_name': 'DnD Reaction',
            },
        ),
    ]
