# Generated by Django 4.0.6 on 2022-10-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0011_alter_pathfindermonster_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='ac_mod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='hp_mod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
