# Generated by Django 4.0.6 on 2022-10-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0012_alter_pathfindermonster_ac_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesheet',
            name='hp_dices',
            field=models.CharField(max_length=255),
        ),
    ]
