# Generated by Django 4.0.6 on 2022-08-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0013_basesheet_home_brew'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesheet',
            name='game',
            field=models.CharField(choices=[('DND5E', 'Dungeons and Dragons 5e'), ('PF2E', 'Pathfinder 2e')], default='', max_length=5),
        ),
    ]
