# Generated by Django 4.0.6 on 2022-10-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0014_alter_pathfindermonster_monster_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesheet',
            name='movement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
