# Generated by Django 4.0.6 on 2022-08-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0014_basesheet_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dndaction',
            old_name='description',
            new_name='action_description',
        ),
        migrations.RenameField(
            model_name='dndaction',
            old_name='name',
            new_name='action_name',
        ),
    ]
