# Generated by Django 4.0.6 on 2022-08-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0015_rename_description_dndaction_action_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dndreaction',
            old_name='description',
            new_name='reaction_description',
        ),
        migrations.RenameField(
            model_name='dndreaction',
            old_name='name',
            new_name='reaction_name',
        ),
        migrations.RenameField(
            model_name='dndskill',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='dndspecialtraits',
            old_name='description',
            new_name='specialtrait_description',
        ),
        migrations.RenameField(
            model_name='dndspecialtraits',
            old_name='name',
            new_name='specialtrait_name',
        ),
    ]
