# Generated by Django 4.0.6 on 2022-10-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0015_alter_basesheet_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='subtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
