# Generated by Django 4.0.6 on 2022-10-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0016_alter_pathfindermonster_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='save_mods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
