# Generated by Django 4.0.6 on 2022-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0020_alter_pathfinderoffense_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderoffense',
            name='attack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
