# Generated by Django 4.0.6 on 2022-11-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0021_alter_pathfinderoffense_attack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndmonster',
            name='condition_immunities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
