# Generated by Django 4.0.6 on 2022-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0022_alter_dndmonster_condition_immunities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndmonster',
            name='damage_resistances',
            field=models.TextField(blank=True, null=True),
        ),
    ]
