# Generated by Django 4.0.6 on 2022-11-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0022_alter_dndmonster_condition_immunities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='fortitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='init',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='monster_alignment',
            field=models.CharField(blank=True, choices=[('LG', 'Lawful Good'), ('LN', 'Lawful Neutral'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('CG', 'Chaotic Good'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil')], default='N', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='reflex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='will',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
