# Generated by Django 4.0.6 on 2022-11-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0023_alter_dndmonster_damage_resistances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndaction',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
