# Generated by Django 4.0.6 on 2022-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0024_alter_dndaction_hit_dice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndaction',
            name='action_name',
            field=models.CharField(max_length=255),
        ),
    ]
